# Generated by Django 5.1.5 on 2025-02-01 12:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('adress', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
