# Generated by Django 5.1.5 on 2025-02-01 12:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contactmodel_delete_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', ckeditor.fields.RichTextField()),
                ('question_hi', models.TextField(blank=True, null=True)),
                ('question_bn', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='contactmodel',
            old_name='adress',
            new_name='address',
        ),
    ]
