# Generated by Django 5.1.5 on 2025-02-02 14:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_contactmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
